import logging

# Configure the basic settings for logging.
# This setup ensures that log messages will have a consistent format and structure, and will be captured at the INFO level or above.
logging.basicConfig(
    level=logging.INFO,  # Set the logging level to INFO, which means only INFO, WARNING, ERROR, and CRITICAL messages will be logged.
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'  # Specify the format of log messages to include:
                                                                   # - %(asctime)s: Timestamp when the log message was created.
                                                                   # - %(name)s: The name of the logger, typically the module name.
                                                                   # - %(levelname)s: The severity level of the log message (e.g., INFO, WARNING).
                                                                   # - %(message)s: The actual log message generated by the application.
)

# Create a logger instance for this module.
# The logger will use the settings defined above, and its name will be the module's name (__name__).
logger = logging.getLogger(__name__)
